server:
    servlet:
        context-path: /api/v1
spring:
    application:
        name: tferp
    datasource:
        #url: 'jdbc:h2:mem:testdb'
        #driverClassName: org.h2.Driver
        url: 'jdbc:mysql://localhost:3306/tferp'
        username: root
        password: root
    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
    flyway:
        enabled: false
        baseline-on-migrate: true
        locations: 'classpath:/db/migration/'
        driver-class-name: org.postgresql.Driver
logging:
    pattern:
        level: '''[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'''
        console: >-
            %p, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L,
            %X{mdc.uuid}, %m%n%ex{3}
    level:
        com:
            erp:
                service: DEBUG
        org:
            springframework:
                data: DEBUG
            flywaydb: DEBUG
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
                sql: DEBUG
quick:
    api:
        parent:
            basePackage: com.erp.tferp
        package:
            controller: controllers
            entity: entities
            service: services
            repository: repositories
springdoc:
    swagger-ui:
        path: /swagger-ui.html
